### ISSUE TITLE
Refresh Cache broken in Background Jobs

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1435]
**Describe the bug**

In staging we see the following error:

```
Starting Background Jobs. 
- starting refreshCache 
Unhandled rejection TypeError: Cannot read property 'set' of 
  at /app/dist/background-jobs.js:82:46 
  at Generator.next (<anonymous>) 
  at Generator.tryCatcher (/app/node_modules/bluebird/js/release/
  at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/
  at Promise._settlePromise (/app/node_modules/bluebird/js/release/
  at Promise._settlePromise0 (/app/node_modules/bluebird/js/release
  at Promise._settlePromises (/app/node_modules/bluebird/js/release
  at Async._drainQueue (/app/node_modules/bluebird/js/release/
  at Async._drainQueues (/app/node_modules/bluebird/js/release/
  at Immediate.Async.drainQueues [as _onImmediate] (/app/
  at runCallback (timers.js:696:18) 
  at tryOnImmediate (timers.js:667:5) 
  at processImmediate (timers.js:649:5) 
```

It's likely related to:
https://github.com/opencollective/opencollective-api/pull/1517

**Comment by znarf** [comment]
@HipsterBrown Can you look into that?
