### ISSUE TITLE
Daily subscription not exiting cleanly

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1574]
From the logs:

```
Running babel-node ./cron/daily/charge_subscriptions.js 
...
Starting to charge subscriptions 
16 subscriptions pending charges. Charging 16 subscriptions right now. dryRun: false 
...
Writing the output to a CSV file 
Sending email report 
Unhandled rejection TypeError: A value undefined was yielded that could not be treated as a promise 
    See http://goo.gl/MqrFmX 
From coroutine: 
    at Promise.coroutine (/app/node_modules/bluebird/js/release/generators.js:190:17) 
    at _run (/app/cron/daily/charge_subscriptions.js:41:34) 
    at run (/app/cron/daily/charge_subscriptions.js:34:15) 
    at run (/app/cron/daily/charge_subscriptions.js:190:11) 
    at Generator.next (<anonymous>) 
    at Generator.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
    at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/release/generators.js:97:49) 
    at /app/node_modules/bluebird/js/release/generators.js:197:15 
    at _entryPoint (/app/cron/daily/charge_subscriptions.js:221:22) 
    at entryPoint (/app/cron/daily/charge_subscriptions.js:204:22) 
    at Object.entryPoint (/app/cron/daily/charge_subscriptions.js:198:1) 
    at Module._compile (internal/modules/cjs/loader.js:702:30) 
    at Module._compile (/app/node_modules/pirates/lib/index.js:83:24) 
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10) 
    at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:88:7) 
    at Module.load (internal/modules/cjs/loader.js:612:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:543:3) 
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10) 
    at Object.<anonymous> (/app/node_modules/@babel/node/lib/_babel-node.js:234:23) 
    at Module._compile (internal/modules/cjs/loader.js:702:30) 
    at PromiseSpawn._continue (/app/node_modules/bluebird/js/release/generators.js:159:21) 
    at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/release/generators.js:99:10) 
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:564:26) 
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:604:10) 
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:683:18) 
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:628:18) 
    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:125:19) 
    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:143:14) 
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:564:26) 
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:604:10) 
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:683:18) 
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:16) 
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14) 
    at runCallback (timers.js:696:18) 
    at tryOnImmediate (timers.js:667:5) 
    at processImmediate (timers.js:649:5) 
```

**Comment by znarf** [comment]
Not reproducible anymore.
