### ISSUE TITLE
Crash on website

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#179]
This morning's crash on website: 

```
Jul 21 07:19:06 opencollective-prod-website app/web.1:  GET / 200 12.795 ms - - 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  /app/server/controllers/banner.js:132 
Jul 21 07:19:06 opencollective-prod-website app/web.1:          var contentType = r.headers['content-type']; 
Jul 21 07:19:06 opencollective-prod-website app/web.1:                             ^ 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  TypeError: Cannot read property 'headers' of undefined 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at Request._callback (banner.js:106:29) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at self.callback (/app/node_modules/request/request.js:200:22) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at emitOne (events.js:90:13) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at Request.emit (events.js:182:7) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at Request.onRequestError (/app/node_modules/request/request.js:831:8) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at emitOne (events.js:90:13) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at ClientRequest.emit (events.js:182:7) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at TLSSocket.socketErrorListener (_http_client.js:306:9) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at emitOne (events.js:90:13) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at TLSSocket.emit (events.js:182:7) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at emitErrorNT (net.js:1265:8) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at _combinedTickCallback (internal/process/next_tick.js:74:11) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:      at process._tickCallback (internal/process/next_tick.js:98:9) 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Linux 3.13.0-91-generic 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start" 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! node v5.11.0 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! npm  v3.8.6 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! code ELIFECYCLE 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! opencollective-website@0.1.144 start: `NODE_CONFIG_DIR=./server/config node server` 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Exit status 1 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR!  
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Failed at the opencollective-website@0.1.144 start script 'NODE_CONFIG_DIR=./server/config node server'. 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Make sure you have the latest version of node.js and npm installed. 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! If you do, this is most likely a problem with the opencollective-website package, 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! not with npm itself. 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Tell the author that this fails on your system: 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR!     NODE_CONFIG_DIR=./server/config node server 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! You can get information on how to open an issue for this project with: 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR!     npm bugs opencollective-website 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Or if that isn't available, you can get their info via: 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR!     npm owner ls opencollective-website 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! There is likely additional logging output above. 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR! Please include the following file with any support request: 
Jul 21 07:19:06 opencollective-prod-website app/web.1:  npm ERR!     /app/npm-debug.log 
Jul 21 07:19:07 opencollective-prod-website heroku/web.1:  State changed from up to crashed 
Jul 21 07:19:07 opencollective-prod-website heroku/web.1:  Process exited with status 1 
```

**Comment by xdamman** [comment]
Probably linked to shields.io being down. 
https://github.com/badges/shields/issues/751

**Comment by xdamman** [comment]
But it shouldn't make our server crash. I'll make a fix.

**Comment by xdamman** [comment]
Here is the PR https://github.com/OpenCollective/opencollective-website/pull/356
