### ISSUE TITLE
error paying for a manual expense

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#197]
```
Jul 26 11:34:31 opencollective-prod-api app/web.1:  Error Express :  { TypeError: Cannot read property 'maxTotalAmountOfAllPayments' of undefined 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.module.exports.formatMessageForPrivateChannel (/app/server/lib/activities.js:109:41) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.module.exports.postActivityOnPrivateChannel (/app/server/lib/slack.js:17:35) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at publishToSlackPrivateChannel (/app/server/lib/notifications.js:66:19) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at module.exports (/app/server/lib/notifications.js:12:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Sequelize.define.hooks.afterCreate (/app/server/models/Activity.js:20:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at /app/node_modules/sequelize/lib/hooks.js:141:19 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:145:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:134:25) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:502:31) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:559:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:596:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:143:12) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at tryOnImmediate (timers.js:543:15) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at processImmediate [as _immediateCallback] (timers.js:523:5) code: 500 } 
Jul 26 11:34:31 opencollective-prod-api app/web.1:  TypeError: Cannot read property 'maxTotalAmountOfAllPayments' of undefined 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.module.exports.formatMessageForPrivateChannel (/app/server/lib/activities.js:109:41) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.module.exports.postActivityOnPrivateChannel (/app/server/lib/slack.js:17:35) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at publishToSlackPrivateChannel (/app/server/lib/notifications.js:66:19) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at module.exports (/app/server/lib/notifications.js:12:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Sequelize.define.hooks.afterCreate (/app/server/models/Activity.js:20:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at /app/node_modules/sequelize/lib/hooks.js:141:19 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:145:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:134:25) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:502:31) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:559:18) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:596:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:143:12) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at tryOnImmediate (timers.js:543:15) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:      at processImmediate [as _immediateCallback] (timers.js:523:5) 
Jul 26 11:34:31 opencollective-prod-api app/web.1:  POST /groups/28/expenses/281/pay?api_key=92083ac82f875336eefa7c5ed276384b 500 381.167 ms - 22 
```

**Comment by asood123** [comment]
Didn't want to wait since this will break every time someone approves a manual payment: https://github.com/OpenCollective/opencollective-api/pull/506
