### ISSUE TITLE
Fragile API test

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2386]
Recently, an API test started to fail randomly on a regular basis. We need to make it more solid.

```graphql.collective.test.js edits edits members - edits members```

```
AssertionError: expected 'ADMIN' to equal 'MEMBER'
    at Context.equal (test/graphql.collective.test.js:805:34)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
    at process.topLevelDomainCallback (domain.js:120:23)
```
Examples:
- https://circleci.com/gh/opencollective/opencollective-api/18483
- https://circleci.com/gh/opencollective/opencollective-api/18669
- https://circleci.com/gh/opencollective/opencollective-api/18674

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs as part as our first Hackathon.

I retroactively added a $100 bounty on it (based on our previous complexity classification, it would have been a "minimal" in today's one). To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
