### ISSUE TITLE
Couldn't recreate the schema DatabaseError: deadlock detected

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2623]
While running API test, it happens that the test suite is failing because of this error.

Sample CI Run: https://circleci.com/gh/opencollective/opencollective-api/21849

Would be great to figure a way to avoid these failures.

```
****/utils.js> Sequelize Error: Couldn't recreate the schema DatabaseError [SequelizeDatabaseError]: deadlock detected
    at Query.formatError (/home/********/project/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
...
    at process.topLevelDomainCallback (domain.js:131:23) {
  name: 'SequelizeDatabaseError',
  parent: error: deadlock detected
      at Connection.parseE (/home/********/project/node_modules/pg/lib/connection.js:604:11)
...
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    name: 'error',
    length: 314,
    severity: 'ERROR',
    code: '40P01',
    detail: 'Process 632 waits for AccessExclusiveLock on relation 91451 of database 20562; blocked by process 634.\n' +
      'Process 634 waits for RowShareLock on relation 91471 of database 20562; blocked by process 632.',
    hint: 'See server log for query details.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'deadlock.c',
    line: '1140',
    routine: 'DeadLockReport',
    sql: 'DROP TABLE IF EXISTS "UpdateHistories" CASCADE;',
    parameters: undefined
  },
  original: error: deadlock detected
      at Connection.parseE (/home/********/project/node_modules/pg/lib/connection.js:604:11)
...
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    name: 'error',
    length: 314,
    severity: 'ERROR',
    code: '40P01',
    detail: 'Process 632 waits for AccessExclusiveLock on relation 91451 of database 20562; blocked by process 634.\n' +
      'Process 634 waits for RowShareLock on relation 91471 of database 20562; blocked by process 632.',
    hint: 'See server log for query details.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'deadlock.c',
    line: '1140',
    routine: 'DeadLockReport',
    sql: 'DROP TABLE IF EXISTS "UpdateHistories" CASCADE;',
    parameters: undefined
  },
  sql: 'DROP TABLE IF EXISTS "UpdateHistories" CASCADE;',
  parameters: undefined
}
```

**Comment by znarf** [comment]
🏆 This issue was completed by @EslamHiko 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new Please make sure to mention the ticket number in the invoice and in the expense title.

**Comment by znarf** [comment]
It's still happening, here for example: https://circleci.com/gh/opencollective/opencollective-api/22330

**Comment by EslamHiko** [comment]
@znarf check my pr: https://github.com/opencollective/opencollective-api/pull/2936
