### ISSUE TITLE
Non breaking error messages in API test

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2696]
<img width="1032" alt="Capture d’écran 2019-12-04 à 15 53 28" src="https://user-images.githubusercontent.com/806/70313451-f4e13080-1815-11ea-8089-ef69d201652e.png">

```
  delete
Unhandled rejection Error: notifyAdminsOfCollective> can't notify collective.comment.created: no collective found with id null
    at /home/********/project/server/lib/notifications.js:11:2531
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/********/project/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/********/project/node_modules/bluebird/js/release/generators.js:97:49)
    at _drainQueueStep (/home/********/project/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/********/project/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/********/project/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/********/project/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)

    ✓ Deletes the conversation when the root comment gets destroyed

  edit
Unhandled rejection Error: notifyAdminsOfCollective> can't notify collective.comment.created: no collective found with id null
    at /home/********/project/server/lib/notifications.js:11:2531
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/********/project/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/********/project/node_modules/bluebird/js/release/generators.js:97:49)
    at _drainQueueStep (/home/********/project/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/********/project/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/********/project/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/********/project/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
```

Sample run: https://circleci.com/gh/opencollective/opencollective-api/23149

Likely happening in `models.Conversations.test.js`.

Bonus: `models.Conversations.test.js` should be wrapped in a root `describe` call like in every other test files.

**Comment by Betree** [comment]
Will be solved in https://github.com/opencollective/opencollective-api/pull/2994 (see https://circleci.com/gh/opencollective/opencollective-api/23170?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
