### ISSUE TITLE
Unhandled Rejection during test

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#2831]
**Describe the bug**
We're getting an Unhandled Rejection from sequelize during our CI tests:
https://github.com/opencollective/opencollective-api/runs/394839067#step:9:34 

```
Unhandled rejection SequelizeForeignKeyConstraintError: insert or update on table "Expenses" violates foreign key constraint "Expenses_CollectiveId_fkey"
    at Query.formatError (/home/runner/work/opencollective-api/opencollective-api/node_modules/sequelize/lib/dialects/postgres/query.js:295:16)
    at /home/runner/work/opencollective-api/opencollective-api/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at tryCatcher (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```

**To Reproduce**
1. Check out any test output in GitHub actions.

**Expected behavior**
We shouldn't have any unhandled rejection.

**Comment by znarf** [comment]
Would be interesting to see when that was introduced. Was not there a few weeks ago.

**Comment by joshikeno** [comment]
I will look into this

**Comment by joshikeno** [comment]
@kewitz can we re-run this test.
I can't find similar error in the recent CI logs and I can't replicate this locally.

**Comment by kewitz** [comment]
@joshikeno apparently this only happens (or is logged) in GitHub actions.
https://github.com/opencollective/opencollective-api/runs/399034225#step:9:21

**Comment by joshikeno** [comment]
@kewitz this rabbit whole is quite deep. 

https://github.com/sequelize/sequelize/issues/4708
https://github.com/sequelize/sequelize/issues/10366
https://github.com/sequelize/sequelize/issues/7826

**Comment by joshikeno** [comment]
@kewitz what are your thought on the root of this issue?

**Comment by znarf** [comment]
We'll handle that internally.
