### ISSUE TITLE
Error while publishing activity

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3071]
```
error:  TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
     at validateString (internal/validators.js:112:11)
     at Url.parse (url.js:155:3)
     at Object.urlParse [as parse] (url.js:150:13)
     at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:66:22)
     at new Promise (<anonymous>)
     at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:21:10)
     at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
   code: 'ERR_INVALID_ARG_TYPE'
```

That can be found in API logs.

**Comment by znarf** [comment]
@kewitz can you look into that?

**Comment by kewitz** [comment]
@znarf, sure, added to the list.

**Comment by kewitz** [comment]
Update: the problem is related to having active webhook notifications in our DB with `webhookUrl = null`.
I'll continue investigating this.
