### ISSUE TITLE
Inconsistent Tests

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3347]
I'm starting a new list with tests that eventually throw in CI workflow so I can fix it in batch.

### How to debug
1. Run the api in E2E mode: `npm run start:e2e`
1. In the Frontend repo, comment the coverage plugin in the frontend:
```patch
diff --git a/test/cypress/plugins/index.js b/test/cypress/plugins/index.js
index a8398bdb3..b833a25e3 100644
--- a/test/cypress/plugins/index.js
+++ b/test/cypress/plugins/index.js
@@ -3,7 +3,7 @@ require('dotenv').config();
 // eslint-disable-next-line
 module.exports = (on, config) => {
   // eslint-disable-next-line node/no-unpublished-require
-  require('@cypress/code-coverage/task')(on, config);
+  // require('@cypress/code-coverage/task')(on, config);
 
   on('before:browser:launch', (browser = {}, launchOptions) => {
     if (browser.name === 'chrome') {
diff --git a/test/cypress/support/index.js b/test/cypress/support/index.js
index ca67250c2..c1764e1ec 100644
--- a/test/cypress/support/index.js
+++ b/test/cypress/support/index.js
@@ -13,7 +13,7 @@
 // https://on.cypress.io/configuration
 // ***********************************************************
 
-import '@cypress/code-coverage/support';
+// import '@cypress/code-coverage/support';
 // Import commands.js using ES2015 syntax:
 import './commands';

```
3. Run the frontend in dev mode: `npm run dev`
4. In the frontend repo, open cypress with `npm run cypress:open`

### List

- [x] Create and Event
```
  Running:  23-event.create.test.js                                                        (4 of 10)


  event.create.test.js
    1) create an event


  0 passing (40s)
  1 failing

  1) event.create.test.js
       create an event:
     AssertionError: Timed out retrying: Expected to find content: 'Saved' within the element: <button.btn.btn-primary> but never did.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/23-event.create.test.js:55:35)
```
- [x] Signin with 2FA
```
  1) signin with 2FA
       can signin with 2fa enabled:
     AssertionError: Timed out retrying: Expected to find element: `.LoginTopBarProfileButton-name`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/support/index.js:33568:27)
```
- [x] Recurring contributions
```
  1) Recurring contributions
       Has contributions in the right categories:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy="recurring-contribution-card"]`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/39-recurring-contributions.test.js:35:59)
```

**Comment by Betree** [comment]
`22-collective.edit.test.js` > `1) edit members` is also often failing:

```
  1) edit collective
       edit members:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy="member-1"]`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/22-collective.edit.test.js:3593:12)
```

**Comment by znarf** [comment]
```
 1) edit collective
       edit tiers:

      AssertionError: Timed out retrying: Too many elements found. Found '8', expected '4'.
      + expected - actual
```

**Comment by kewitz** [comment]
```
1) Internationalization
       Can switch language from the footer:
     AssertionError: Timed out retrying: Expected to find content: '🇫🇷 French - Français (100%)' within the selector: '[data-cy="select-option"]' but never did.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/00-i18n.test.js:6:12)
```

**Comment by znarf** [comment]
@kewitz lol, I just commited to master changes in the percentages. I was not thinking it could break anything!

Not a good idea to rely on that in tests :-)

**Comment by kewitz** [comment]
@znarf it shouldn't, comparing the percentage is unnecessary for the test's sake.

**Comment by flickz** [comment]
About to open a PR to fix this.

**Comment by znarf** [comment]
```
 Collective to Collective Transactions
   Recurring donations between Collectives with the same host must be allowed:

AssertionError: expected false to be true
```

**Comment by znarf** [comment]
```
Running:  39-recurring-contributions.test.js

1) Recurring contributions
       Can add a new payment method and use it for the recurring contribution:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy="new-credit-card-form"]`, but never found it.
```

**Comment by sbinlondon** [comment]
![Screenshot 2020-08-17 at 13 49 19](https://user-images.githubusercontent.com/37520401/90397967-90f35500-e090-11ea-86d0-a08dd428f620.png)

This one has been flaking for me a lot lately. Never on local, but quite a few times on Github, and if you rerun it eventually passes.

**Comment by znarf** [comment]
@sbinlondon duplicate with https://github.com/opencollective/opencollective/issues/3347#issuecomment-673432174

**Comment by znarf** [comment]
```
Running:  39-recurring-contributions.test.js                  

1) Recurring contributions
       Can add a new payment method and use it for the recurring contribution:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy="new-credit-card-form"]`, but never found it.
```

**Comment by Betree** [comment]
@kewitz I'd like to look at some of these tests today. Is that ok for you? Any info to share before I start digging?

**Comment by kewitz** [comment]
@Betree sure! Feel free to tackle any test you want and check it down.
I added some instructions on how I was debugging it locally in the Issue description, the problem is that I feel like there's a set of problems that won't show locally and I'm not sure why.
Perhaps these tests are co-dependent.

**Comment by znarf** [comment]
E2E 39 is still failing a lot and is the most problematic as of today. cc @Betree @sbinlondon

**Comment by sbinlondon** [comment]
For me the 'edit collective' (number 22 I think?) is by far the most problematic. It's failed lots over a few of my latest PRs. I haven't had issues with 39 in weeks.

I can try and have a look at it this week, but didn't @kewitz make some changes recently that helped to make it more consistent?

**Comment by znarf** [comment]
@sbinlondon 22 is also failing a lot that's true. I quickly looked at today's PR failures, and easily found 4 with E2E 39. There is definitely more as I already restarted many tests.

Bottom line, if we succeed fixing 22 and 39, we will be in a way better place.

**Comment by sbinlondon** [comment]
It was on my mental checklist to look at 22 from last week so I can do that. Happy to try fixing 39 too unless anyone else wants to take one of those.

**Comment by Betree** [comment]
I just had an epiphany on what could be wrong with `22`, I'll look at it now!

**Comment by kewitz** [comment]
```
1) server/graphql/v1/collective
       allMembers query
         gets totalAmountSpent by collective:
     AssertionError: expected [ Array(1) ] to not exist
      at Context.<anonymous> (test/server/graphql/v1/collective.test.js:827:7)
      at Generator.next (<anonymous>)
      at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by znarf** [comment]
New form of E2E 39 failure:

```
  1) Recurring contributions
       Can add a new payment method and use it for the recurring contribution:
     AssertionError: Timed out retrying: Expected to find element: `.__PrivateStripeElement iframe`, but never found it.
```

- https://github.com/opencollective/opencollective-api/pull/4459/checks?check_run_id=1033902562

**Comment by Betree** [comment]
I'm currently rewriting the `fillStripeInput` with a better understanding of Cypress (thanks to https://www.cypress.io/blog/2020/01/16/when-can-the-test-stop/). I hope it will help to solve issues with payments, in particular the ones like https://github.com/opencollective/opencollective/issues/3347#issuecomment-681736166

**Comment by sbinlondon** [comment]
@Betree How did this go?

**Comment by Betree** [comment]
Part of it is https://github.com/opencollective/opencollective-frontend/pull/5022, but it's not a silver bullet. I had to add a `cy.wait`, which defeats the purpose of the PR (having Cypress to detect that the iframe is loaded). Until this is resolved, the best is usually to put a `cy.wait(3000)` before any `cy.fillStripeInput`

**Comment by sbinlondon** [comment]
Potentially fixed test 39 here: https://github.com/opencollective/opencollective-frontend/pull/5115

**Comment by sbinlondon** [comment]
Narrator: it was indeed fixed! 🎉

**Comment by Betree** [comment]
API `server/lib/onboarding` was failing a lot for me:
```
  1) server/lib/onboarding
       sends onboarding after 2 days for new organizations:

      AssertionError: expected 'testadminuser2@gmail.com' to equal 'testadminuser1@gmail.com'
      + expected - actual

      -testadminuser2@gmail.com
      +testadminuser1@gmail.com
      
      at map (test/server/lib/onboarding.test.js:55:45)
      at Array.map (<anonymous>)
      at Context.<anonymous> (test/server/lib/onboarding.test.js:53:12)
      at Generator.next (<anonymous>)
      at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
```
I'm currently trying a fix for it.

**Comment by Betree** [comment]
Test `39` still failing very often for me with:

> Timed out retrying: Expected to find element: `.__PrivateStripeElement iframe`, but never found it.

Could be nice to disable it while we figure out what's wrong.

**Comment by kewitz** [comment]
```  
1) test/server/models/Expense
       Create
         Must be a valid emoji:
     SequelizeUniqueConstraintError: Validation error
      at Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:324:18)
      at /home/runner/work/opencollective-api/opencollective-api/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by Betree** [comment]
This API test is failing a lot lately:

```
server/graphql/v1/transaction
       return transactions
         `transactions` query
           accepts pagination arguments: limit & offset:
```

<details>
<summary>Details</summary>

```
AssertionError: expected value to match snapshot server/graphql/v1/transaction return transactions `transactions` query accepts pagination arguments: limit & offset 1
      + expected - actual

             "total": 20,
             "transactions": Array [
               Object {
                 "collective": Object {
      -            "id": 3,
      -            "slug": "wwcodeaustin",
      +            "id": 7,
      +            "slug": "holly-day",
                 },
                 "createdByUser": Object {
                   "email": null,
                   "firstName": null,
                   "id": 5,
                   "lastName": null,
                 },
                 "fromCollective": Object {
      -            "id": 7,
      -            "slug": "holly-day",
      +            "id": 3,
      +            "slug": "wwcodeaustin",
                 },
                 "host": Object {
                   "id": 2,
                   "slug": "wwcode",
                 },
      -          "id": 10,
      -          "paymentMethod": Object {
      -            "id": 8,
      -            "name": null,
      -          },
      -          "subscription": null,
      -          "type": "CREDIT",
      +          "id": 9,
      +          "type": "DEBIT",
               },
               Object {
                 "collective": Object {
      -            "id": 3,
      -            "slug": "wwcodeaustin",
      +            "id": 6,
      +            "slug": "geoff-frey",
                 },
                 "createdByUser": Object {
                   "email": null,
                   "firstName": null,
                   "id": 4,
                   "lastName": null,
                 },
                 "fromCollective": Object {
      -            "id": 6,
      -            "slug": "geoff-frey",
      +            "id": 3,
      +            "slug": "wwcodeaustin",
                 },
                 "host": Object {
                   "id": 2,
                   "slug": "wwcode",
                 },
      -          "id": 6,
      -          "paymentMethod": Object {
      -            "id": 6,
      -            "name": null,
      -          },
      -          "subscription": null,
      -          "type": "CREDIT",
      +          "id": 5,
      +          "type": "DEBIT",
               },
               Object {
                 "collective": Object {
      -            "id": 6,
      -            "slug": "geoff-frey",
      +            "id": 3,
      +            "slug": "wwcodeaustin",
                 },
                 "createdByUser": Object {
                   "email": null,
                   "firstName": null,
                   "id": 4,
                   "lastName": null,
                 },
                 "fromCollective": Object {
      -            "id": 3,
      -            "slug": "wwcodeaustin",
      +            "id": 6,
      +            "slug": "geoff-frey",
                 },
                 "host": Object {
                   "id": 2,
                   "slug": "wwcode",
                 },
      -          "id": 5,
      -          "type": "DEBIT",
      +          "id": 6,
      +          "paymentMethod": Object {
      +            "id": 6,
      +            "name": null,
      +          },
      +          "subscription": null,
      +          "type": "CREDIT",
               },
               Object {
                 "collective": Object {
                   "id": 5,
      
      at Context.<anonymous> (test/server/graphql/v1/transaction.test.js:397:27)
      at Generator.next (<anonymous>)
      at Generator.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

</details>

**Comment by Betree** [comment]
Test `27-expenses` is failing pretty often:

```
  1) New expense flow
       new expense when logged in
         can create a new organization:
     AssertionError: Timed out retrying: Expected to find element: `textarea[name="payoutMethod.data.content"]`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/27-expenses.test.js:985:16)
```

**Comment by Betree** [comment]
Another one failing very often for me:
```
   1) server/lib/spam
       collectiveSpamCheck
         detects blocked websites:

      AssertionError: expected { Object (date, score, ...) } to deeply equal { Object (score, keywords, ...) }
      + expected - actual

         "date": "2020-01-01T00:00:00.000Z"
         "domains": [
           "supplementslove.com"
         ]
      -  "keywords": [
      -    "cbd"
      -  ]
      +  "keywords": []
         "score": 1
       }
```

**Comment by Betree** [comment]
`12-contributionFlow.donate.test.js` is failing very often for me lately.
```
  Contribution Flow: Donate
    ✓ Can donate as new user (27261ms)
    ✓ Can donate as new organization (16212ms)
    ✓ Forces params if given in URL (11396ms)
    1) works with 3D secure


  3 passing (2m)
  1 failing

  1) Contribution Flow: Donate
       works with 3D secure:
     AssertionError: Timed out retrying: Expected to find content: 'We are unable to authenticate your payment method.' but never did.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/12-contributionFlow.donate.test.js:130:12)
```

**Comment by Betree** [comment]
Mentioning something that was shared by @SudharakaP in https://github.com/opencollective/opencollective/issues/4192#issuecomment-833589448: we're now using the latest version of Cypress that supports [retries](https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations). That should not prevent us from fixing flaky tests, but it can help with things that are unreliable for reasons we don't have much control over (Stripe iframes for example).

**Comment by kewitz** [comment]
E2E tests are a lot stable and we'll track specific problems in independent issues from now on.
