### ISSUE TITLE
Error when paging through expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3874]
**Describe the bug**
I'm trying to load https://opencollective.com/opensource/expenses?offset=40 but I get this error.

Message
Cannot read property 'type' of null
Cannot return null for non-nullable field Expense.payee.

Trace
Error: Cannot read property 'type' of null
Cannot return null for non-nullable field Expense.payee.
    at new t (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:209917)
    at t.i.getQueryResult (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:144362)
    at t.getExecuteResult (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:147002)
    at t.execute (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:145886)
    at https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:151161
    at https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:151099
    at v (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:151121)
    at m (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:151952)
    at c (https://opencollective.com/_next/static/chunks/d276cbb101becf174acda2185622f366e203c614.c2e2911be712e3c49998.js:1:137205)
    at Gi (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:90915)
    at Vo (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:99815)
    at xa (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:138381)
    at yu (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:129872)
    at mu (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:129797)
    at au (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:126806)
    at https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78177
    at t.unstable_runWithPriority (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:3950)
    at Bl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:77886)
    at Xl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78122)
    at Yl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78057)
    at nu (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:123588)
    at bo (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:95288)

**Comment by Betree** [comment]
Associated Sentry error: https://sentry.io/organizations/open-collective/issues/2166233958/?project=5199682&query=Cannot+return+null+for+non-nullable+field+Expense.payee.&statsPeriod=14d

**Comment by znarf** [comment]
Guess we're gonna discover that an account was deleted when it shouldn't, let's see.

**Comment by znarf** [comment]
That might be on me. In December, I was trying to delete all the mess created by a spammer and missed to delete 2 expenses.
