### ISSUE TITLE
Problem creating donation

### ISSUE THREAD

**Issue by darkdragon-001** [opencollective/opencollective#3933]
**Describe the bug**
Error message _Ooops, an unexpected error seems to have occurred  🤕_.

**To Reproduce**
1. Click on contribute on any project
2. Select amount
3. Click on "Your info ->"
5. Click on "Reload the page"
6. It is now on step 2 (profile), but the amount has been reset to the default value!!!

**Expected behavior**
Either use the user defined amount or go back to step one.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Chrome
 - Version: 87.0.4280.141

**Additional context**
DevTool show the following exception:
<details><pre>
instrument.js:109 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at va (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:119763)
    at ku (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:133016)
    at t.unstable_runWithPriority (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:3950)
    at Bl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:77886)
    at wu (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:130874)
    at au (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:127005)
    at https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78177
    at t.unstable_runWithPriority (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:3950)
    at Bl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:77886)
    at Xl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78122)
    at Yl (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:78057)
    at R (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:147343)
    at Xt (https://opencollective.com/_next/static/chunks/framework.72bef9cae578a18122fd.js:1:55328)
    at HTMLDocument.r (https://opencollective.com/_next/static/chunks/pages/_app-4eccbc066735cac61f83.js:1:61883)
</details></pre>

**Comment by Betree** [comment]
I can't reproduce on Linux Mint with a close Chrome version (`87.0.4280.88 (Official Build)`). However [Sentry](https://sentry.io/organizations/open-collective/issues/1574827166) reports indicate that multiple people faced this issue.

@darkdragon-001 what was the collective you tried to contribute to?

**Comment by darkdragon-001** [comment]
It happens with all collectives (e.g. KeePassXC). It doesn't happen when using the incognito browser. After clearing all local data for opencollective.com, it also appears less often.

I can still reproduce it when going fast between step 1 and step 3 of donating.

**Comment by Betree** [comment]
@darkdragon-001 thank you for these details. The fact that it doesn't happen when using incognito might reveal a conflict with a browser extension (eg. an ad blocker for example). Could you share with me which browser extensions are currently enabled on your Chrome? If you don't want to share this publicly, feel free to ping me on [Slack](https://slack.opencollective.com/)
