### ISSUE TITLE
Broken Vercel pre-deploys

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4102]
See https://opencollective-frontend-2hmsmuofa-opencollective.vercel.app/

Looking at [the history](https://github.com/opencollective/opencollective-frontend/commits/main?after=02595bdbb2d17f18326f52e3d7f7439e0d37c200+209&branch=main), it started being buggy around https://github.com/opencollective/opencollective-frontend/pull/5971 but [reverting](https://github.com/opencollective/opencollective-frontend/pull/6092) the library doesn't seem to solve the problem.

The [build logs](https://vercel.com/opencollective/opencollective-frontend/CZYVE5voZZKMJwr82HeA8Q8LLDt6) don't indicate any specific problems, no do the [server logs](https://vercel.com/opencollective/opencollective-frontend/CZYVE5voZZKMJwr82HeA8Q8LLDt6/functions).

**Comment by Betree** [comment]
Interesting error when trying to view a collective page:

![image](https://user-images.githubusercontent.com/1556356/111978545-4c3b0b00-8b04-11eb-9395-b662d58560bf.png)


> [POST] /api/graphql/v1
> 11:45:35:31
> 2021-03-22T10:45:36.644Z	876cfe0e-575b-4f0a-a85d-b7585a9474f5	ERROR	Error: Cannot find module '/var/task/.next/server/pages/404.js'Require stack:- /var/task/node_modules/next/dist/next-server/server/require.js- /var/task/node_modules/next/dist/next-server/server/load-components.js- /var/task/node_modules/next/dist/next-server/server/api-utils.js- /var/task/node_modules/next/dist/next-server/server/next-server.js- /var/task/___next_launcher.js- /var/runtime/UserFunction.js- /var/runtime/index.js    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)    at Function.Module._load (internal/modules/cjs/loader.js:725:27)    at Module.require (internal/modules/cjs/loader.js:952:19)    at require (internal/modules/cjs/helpers.js:88:18)    at requirePage (/var/task/node_modules/next/dist/next-server/server/require.js:1:1184)    at loadComponents (/var/task/node_modules/next/dist/next-server/server/load-components.js:1:948)    at async Server.findPageComponents (/var/task/node_modules/next/dist/next-server/server/next-server.js:74:257)    at async Server.renderErrorToHTML (/var/task/node_modules/next/dist/next-server/server/next-server.js:136:18)    at async Server.renderError (/var/task/node_modules/next/dist/next-server/server/next-server.js:135:1659)    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:1232) {  code: 'MODULE_NOT_FOUND',  requireStack: [    '/var/task/node_modules/next/dist/next-server/server/require.js',    '/var/task/node_modules/next/dist/next-server/server/load-components.js',    '/var/task/node_modules/next/dist/next-server/server/api-utils.js',    '/var/task/node_modules/next/dist/next-server/server/next-server.js',    '/var/task/___next_launcher.js',    '/var/runtime/UserFunction.js',    '/var/runtime/index.js'  ]}RequestId: 876cfe0e-575b-4f0a-a85d-b7585a9474f5 Error: Runtime exited with error: exit status 1Runtime.ExitError
