### ISSUE TITLE
Error Updating Tests: `npm run test:update`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4305]
**Describe the bug**

It seems that running `npm run test:update` gives the following error. 😄 

```
error: uncaughtException: self._addDefaultMeta is not a function
TypeError: self._addDefaultMeta is not a function
    at DerivedLogger.<computed> (/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)
    at /home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:171:23) {"error":{},"stack":"TypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:171:23)","exception":true,"date":"Thu May 20 2021 05:11:23 GMT+0000 (Coordinated Universal Time)","process":{"pid":49206,"uid":1000,"gid":1000,"cwd":"/home/sudharaka/IdeaProjects/opencollective-api","execPath":"/home/sudharaka/.nvm/versions/node/v14.16.1/bin/node","version":"v14.16.1","argv":["/home/sudharaka/.nvm/versions/node/v14.16.1/bin/node","/home/sudharaka/IdeaProjects/opencollective-api/node_modules/.bin/mocha"],"memoryUsage":{"rss":925995008,"heapTotal":733220864,"heapUsed":412161080,"external":2311300,"arrayBuffers":557271}},"os":{"loadavg":[1.12,0.6,0.41],"uptime":59625},"trace":[{"column":14,"file":"/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js","function":"DerivedLogger.<computed>","line":80,"method":"<computed>","native":false},{"column":14,"file":"/home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js","function":null,"line":61,"method":null,"native":false},{"column":23,"file":"fs.js","function":"FSReqCallback.oncomplete","line":171,"method":"oncomplete","native":false}]}
{"error":{},"level":"error","message":"uncaughtException: self._addDefaultMeta is not a function\nTypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:171:23)","stack":"TypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:171:23)","exception":true,"date":"Thu May 20 2021 05:11:23 GMT+0000 (Coordinated Universal Time)","process":{"pid":49206,"uid":1000,"gid":1000,"cwd":"/home/sudharaka/IdeaProjects/opencollective-api","execPath":"/home/sudharaka/.nvm/versions/node/v14.16.1/bin/node","version":"v14.16.1","argv":["/home/sudharaka/.nvm/versions/node/v14.16.1/bin/node","/home/sudharaka/IdeaProjects/opencollective-api/node_modules/.bin/mocha"],"memoryUsage":{"rss":925995008,"heapTotal":733220864,"heapUsed":412161080,"external":2311300,"arrayBuffers":557271}},"os":{"loadavg":[1.12,0.6,0.41],"uptime":59625},"trace":[{"column":14,"file":"/home/sudharaka/IdeaProjects/opencollective-api/node_modules/winston/lib/winston/create-logger.js","function":"DerivedLogger.<computed>","line":80,"method":"<computed>","native":false},{"column":14,"file":"/home/sudharaka/IdeaProjects/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js","function":null,"line":61,"method":null,"native":false},{"column":23,"file":"fs.js","function":"FSReqCallback.oncomplete","line":171,"method":"oncomplete","native":false}]}
```
Investigating further it seems that this stemmed from the `winston` dependency upgrade. The relevant issue is; https://github.com/winstonjs/winston/issues/1591. As a workaround, downgrading to `winston 3.1.0` seems to work.

**Comment by Betree** [comment]
Or I wonder if it wasn't related to the node version...

**Comment by SudharakaP** [comment]
@Betree : Thanks for the help. 😄 

> I saw this one in the past, but I'm not sure how I resolved it. Maybe try an `rm -rf node_modules && npm install`?

I tried this just now but didn't work unfortunately. 

> Or I wonder if it wasn't related to the node version...

You meant if it "was" related to the node version? Maybe, I am using 14.16.1 currently. 🤔

**Comment by Betree** [comment]
> You meant if it "was" related to the node version? Maybe, I am using 14.16.1 currently. 

I'm using `14.8.0` and it's working so far, so I'm not sure

**Comment by SudharakaP** [comment]
Look at this CI run; very interesting; it gets the same error I got; https://github.com/opencollective/opencollective-api/pull/6062/checks?check_run_id=2632023471. Maybe this happens intermittently. 🤔

**Comment by SudharakaP** [comment]
This seems no longer an issue, and hence I am closing this. I think this only effected me and I am not sure what was going on at that time in my machine. 🤔

**Comment by FluxZA** [comment]
I ran into the same issue when running tests and it also showed up when running CI on my pull request. My setup is fresh as I am working on my first issue for Open Collective. I did some digging based on the issue linked by @SudharakaP  and narrowed it down to the following function in [awsS3.ts](https://github.com/opencollective/opencollective-api/blob/5526eb5fe56cdee6f43f0eda5662dedce66d482e/server/lib/awsS3.ts#L19-L38). In particular the highlighted line:

```node
export const uploadToS3 = (
  params: PutObjectRequest,
): Promise<ManagedUpload.SendData | { Location: string; Bucket: string; Key: string }> =>
  new Promise((resolve, reject) => {
    if (s3) {
      (s3 as S3).upload(params, (err, data) => {
        if (err) {
          logger.error('Error uploading file to S3: ', err);
          reject(err);
        } else {
          resolve(data);
        }
      });
    } else {
      const Location = `/tmp/${params.Key}`;
      logger.warn(`S3 is not set, saving file to ${Location}. This should only be done in development.`);
// >>>>
      fs.writeFile(Location, params.Body, logger.info); // This line throws
// >>>>
      resolve({ Location: `file://${Location}`, Bucket: 'local-tmp', Key: params.Key });
    }
  });`
```

I think that it may only occur is some cases, because the call only happens if s3 is false. I don't know if s3 is always false during tests, or if it is something I did not setup. Binding the info function to the logger fixes the issue for me.

```node
 fs.writeFile(Location, params.Body, logger.info.bind(logger));
```

**Comment by znarf** [comment]
On CI on your own repository, it's likely that S3 is not configured in the environment variables while it is in opencollective own repository.

**Comment by FluxZA** [comment]
Thanks for the info. Would that suggest that the error occurring during the checks on the pull request is happening for another reason?

**Comment by SudharakaP** [comment]
> Small note. On CI on your own repository, it's likely that S3 is not configured in the environment variables while it is in opencollective own repository.

Ah, that might be the issue; but recently I didn't see it anymore, but will keep a tab on it.
