### ISSUE TITLE
`schema-update` CI Failure

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5016]
It seems that starting recently the `schema-update` GitHub action fails on the API side for almost all pull requests with the following error;

```
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,hbs,ts
[nodemon] starting `babel-node --extensions .js,.ts server/index.js .`
error: uncaughtException: The module '/home/runner/work/opencollective-api/opencollective-api/node_modules/re2/build/Release/re2.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/home/runner/work/opencollective-api/opencollective-api/node_modules/re2/build/Release/re2.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/opencollective-api/opencollective-api/node_modules/re2/re2.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/runner/work/opencollective-api/opencollective-api/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/home/runner/work/opencollective-api/opencollective-api/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by SudharakaP** [comment]
I think this is an instance where out GitHub actions cache is corrupt. For example the latest renovate PR; https://github.com/opencollective/opencollective-api/pull/6920 which doesn't use the existing cache passes all tests without issue. Currently there's [no way in GitHub Actions to clear the cache through the UI](https://github.com/actions/cache/issues/2). Maybe as a workaround we can use the solution proposed here; https://github.com/actions/cache/issues/2#issuecomment-861071749 where action secrets are used to refresh the cache. If this is of value I can propose a PR. WDYT? 🤔 

cc: @opencollective/core-developers

**Comment by Betree** [comment]
@SudharakaP Feel free to open an PR to demo that

**Comment by SudharakaP** [comment]
Looking at this further I think the cache invalidation alone seems not to solve this; although it seems to sometimes pass the `schema-update` when restarting CI after invalidating the cache seems it's not consistent. I think the root cause is that on Nov 29th they updated default node version in all github CI environments to node 16; https://github.com/actions/virtual-environments/issues/4446. So I think the above PR by @Betree specifying the node version should solve the issue. 🤔
