### ISSUE TITLE
error message "The slug agent is already taken. Please use another slug for your collective" but the collective has been created

### ISSUE THREAD

**Issue by scenaristeur** [opencollective/opencollective#5807]
**Describe the bug**
Creating a first collective called "Agent" i've got an error in the UI saying saying "the slug 'Agent' already exist"

frontend "version": "2.2.0",

confirmed by opencollective-api 
```
error: GraphQL error: The slug agent is already taken. Please use another slug for your collective.
error: {"locations":[{"line":2,"column":3}],"path":["createCollective"]}
error: Error: The slug agent is already taken. Please use another slug for your collective.,    at /home/smag/dev/opencollective/api/server/graphql/v2/mutation/CreateCollectiveMutation.js:82:15,    at Generator.next (<anonymous>),    at Generator.tryCatcher (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/util.js:16:23),    at PromiseSpawn._promiseFulfilled (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/generators.js:97:49),    at Promise._settlePromise (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:609:26),    at Promise._settlePromise0 (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:649:10),    at Promise._settlePromises (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:729:18),    at _drainQueueStep (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:93:12),    at _drainQueue (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:86:9),    at Async._drainQueues (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:102:5),    at Immediate.Async.drainQueues [as _onImmediate] (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:15:14),    at processImmediate (node:internal/timers:466:21),    at process.topLevelDomainCallback (node:domain:152:15),    at process.callbackTrampoline (node:internal/async_hooks:128:24)
error: GraphQL error: The slug agent is already taken. Please use another slug for your collective.
error: {"locations":[{"line":2,"column":3}],"path":["createCollective"]}
error: Error: The slug agent is already taken. Please use another slug for your collective.,    at /home/smag/dev/opencollective/api/server/graphql/v2/mutation/CreateCollectiveMutation.js:82:15,    at Generator.next (<anonymous>),    at Generator.tryCatcher (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/util.js:16:23),    at PromiseSpawn._promiseFulfilled (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/generators.js:97:49),    at Promise._settlePromise (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:609:26),    at Promise._settlePromise0 (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:649:10),    at Promise._settlePromises (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/promise.js:729:18),    at _drainQueueStep (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:93:12),    at _drainQueue (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:86:9),    at Async._drainQueues (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:102:5),    at Immediate.Async.drainQueues [as _onImmediate] (/home/smag/dev/opencollective/api/node_modules/bluebird/js/release/async.js:15:14),    at processImmediate (node:internal/timers:466:21),    at process.topLevelDomainCallback (node:domain:152:15),    at process.callbackTrampoline (node:internal/async_hooks:128:24)


```

But the collective "Agent" has been created

**Comment by Betree** [comment]
Could you add some steps to reproduce? Did you create the collective directly from the API, from the UI?

**Comment by scenaristeur** [comment]
I can not reproduce it was only for the first created.
