### ISSUE TITLE
Unreliable API Unit Tests

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6564]
To document tests failing too often.

**Comment by Betree** [comment]
```
test/server/lib/payments.test.js
1) successfully sends out an email to donor
```

=> https://github.com/opencollective/opencollective-api/pull/8694

**Comment by Betree** [comment]
- https://github.com/opencollective/opencollective/issues/6533

**Comment by Betree** [comment]
The test for `server/lib/notification` needs to be optimized, we [increased](https://github.com/opencollective/opencollective-api/pull/8673) its timeout to 50s but it is not sustainable to have a test that stays locked for this long.

**Comment by Betree** [comment]
```
1) server/graphql/v2/mutation/AccountMutations
     "before all" hook in "server/graphql/v2/mutation/AccountMutations":
   Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/opencollective-api/opencollective-api/test/server/graphql/common/scope-check.test.ts)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Comment by Betree** [comment]
Not an error, but our test logs are polluted with:

```
Error: notify.collective can't notify collective.expense.error: no collective found with id 4
    at /home/runner/work/opencollective-api/opencollective-api/server/lib/notifications/email.ts:1:32
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/opencollective-api/opencollective-api/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:476:21)
```

**Comment by Betree** [comment]
1) server/graphql/v2/mutation/ExpenseMutations
       processExpense > PAY > with 2FA payouts
         Pays multiple expenses - 2FA is asked for the first time and after the limit is exceeded:
     AssertionError: expected [ GraphQLError{ …(10) } ] to not exist
      at Context.<anonymous> (test/server/graphql/v2/mutation/ExpenseMutations.test.js:3466:36)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Betree** [comment]
```
  1) server/models/Order
       lock
         retries the lock if it fails:
     Error: This order is already been processed, please try again later
      at model.Order.lock (server/models/Order.ts:592:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 0)
      at Context.<anonymous> (test/server/models/Order.test.js:77:53)
```

**Comment by Betree** [comment]
```
  1) lockUntilResolved
       should wait for the first lock to finish:
     AssertionError: expected 34 to be close to 25 +/- 5
      at Context.<anonymous> (test/server/lib/mutex.test.ts:36:14)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) lockUntilResolved
       releases the lock if the callback function fails:
     AssertionError: expected 41 to be close to 25 +/- 5
      at Context.<anonymous> (test/server/lib/mutex.test.ts:60:14)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Betree** [comment]
```
1) server/graphql/v2/mutation/ExpenseMutations
       editExpense
         DRAFT
           send notification to invited external user when DRAFT is updated:
     AssertionError: expected sendMessage to have been called with arguments 'test@email.com', 'An expense you were invited to submit has been updated'
'"test-user-p1vtk0vried@emailprovider.com"' '"test@email.com"' 
'"An expense you were invited to submit has been updated"'
`"<!DOCTYPE html PUBLIC \\"-//W3C//DTD XHTML 1.0 Transitional//EN\\" \\"[http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\\](http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd//)">\\n<html xmlns=\\"[http://www.w3.org/1999/xhtml\\](http://www.w3.org/1999/xhtml//)">\\n<head>\\n  <meta http-equiv=\\"Content-Type\\" content=\\"text/html; charset=UTF-8\\">\\n  <title></title>\\n  <style>\\n@media only screen and (min-device-width: 601px) {\\n  .content {\\n    width: 600px !important;\\n  }\\n}\\n.btn.blue:hover {\\n  background: linear-gradient(180deg,#297EFF 0%,#1869F5 100%);\\n  background-color: #297EFF;\\n  border-color: #297EFF;\\n  color: #FFFFFF;\\n}\\n</style>\\n</head>\\n<body margin=\\"0\\" padding=\\"0\\" yahoo style=\\"margin: 0; padding: 0; min-width: 100%;\\">\\n\\n<table bgcolor=\\"white\\" border=\\"0\\" cellpadding=\\"0\\" cellspacing=\\"0\\" width=\\"100%\\" style=\\"font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:14px;\\"><tr><td align=\\"center\\" valign=\\"top\\">\\n  <!--[if (gte mso 9)|(IE)]>\\n    <table width=\\"600\\" align=\\"center\\" cellpadding=\\"0\\" cellspacing=\\"0\\" border=\\"0\\"><tr><td>\\n  <![endif]-->\\n  <table class=\\"content\\" border=\\"0\\" width=\\"100%\\" cellpadding=\\"0\\" cellspacing=\\"0\\" style=\\"width: 100%; max-width: 600px; padding: 0 10px;\\">\\n    <tr>\\n      <td></td>\\n      <td>\\n\\n<center>\\n  <h3 style=\\"color: #303233; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 20px; font-weight: bold; line-height: 25px;\\">An expense for Test Collective 22ae07cf has been updated.</h3>\\n  <h2 style=\\"color: #303233; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; font-size: 20px; line-height: 24px; text-align: center;\\"><a href=\\"http://localhost:3000/collective-0d7af46f/expenses/51\\" style=\\"text-decoration: none; color: #297EFF;\\">This is a test.</a></h2>\\n  <div>\\n    Payee: <a href=\\"http://localhost:3000/user-0587f2b8\\" style=\\"text-decoration: none; color: #297EFF;\\"> User Name08bcdba3 </a>\\n  </div>\\n\\n  <br>\\n  <br>\\n  <br>\\n  <a class=\\"btn blue\\" href=\\"http://localhost:3000/collective-0d7af46f/expenses/51\\" style=\\"text-decoration: none; padding: 10px; border: 1px solid #3399FF; border-radius: 16px; display: inline-block; font-weight: 600; font-size: 14px; line-height: 17px; padding-bottom: 14px; padding-left: 24px; padding-right: 24px; padding-top: 14px; border-radius: 100px; min-height: 18px; background-color: #3399FF; background: linear-gradient(180deg,#1869F5 0%,#1258e2 100%); background-color: #1869F5; border-color: #1869F5; color: #FFFFFF;\\">\\n    <div style=\\"font-family: 'Inter', sans-serif; font-weight: 600; font-size: 14px; line-height: 17px; font-size: 12px; text-align: center; color: white;\\">View Expense</div>\\n  </a>\\n\\n  <br><br>\\n</center>\\n\\n</td>\\n</tr>\\n<tr>\\n  <td colspan=\\"3\\" height=\\"40\\"></td>\\n</tr>\\n<tr>\\n  <td colspan=\\"3\\" align=\\"center\\">\\n    <table width=\\"100%\\">\\n      <tr>\\n        <td></td>\\n        <td width=\\"200\\">\\n          <a href=\\"http://localhost:3000\\" style=\\"text-decoration: none; color: #297EFF;\\">\\n            <img width=\\"220\\" height=\\"28\\" src=\\"http://localhost:3000/static/images/email/logo-email-footer@2x.png\\" style=\\"max-width: 100%;\\">\\n          </a>\\n        </td>\\n        <td></td>\\n      </tr>\\n    </table>\\n  </td>\\n</tr>\\n<tr>\\n  <td colspan=\\"3\\" align=\\"center\\" style=\\"font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;box-sizing:border-box;font-size:12px;color:#999;\\">\\n    We can do great things together<br><br>\\n\\n    You can also follow us on <a href=\\"[https://twitter.com/OpenCollect\\](https://twitter.com/OpenCollect//)" style=\\"text-decoration: none; color: #297EFF;\\">Twitter</a> or come chat with us on our public\\n    <a href=\\"[https://discord.opencollective.com\\](https://discord.opencollective.com//)" style=\\"text-decoration: none; color: #297EFF;\\">Discord</a>.\\n    <br><br>\\n    Made with ❤️ from <a href=\\"[https://docs.opencollective.com/help/about/team\\](https://docs.opencollective.com/help/about/team//)" style=\\"text-decoration: none; color: #297EFF;\\">all over the world</a>\\n  </td>\\n</tr>\\n<tr>\\n  <td colspan=\\"3\\" height=\\"10\\"></td>\\n</tr>\\n</table><!-- 600px width content table -->\\n\\n<!--[if (gte mso 9)|(IE)]>\\n  </td></tr></table>\\n<![endif]-->\\n\\n</td>\\n</tr>\\n</table><!-- 100% width table -->\\n<!-- OpenCollective.com -->\\n</body>\\n\\n</html>"`
{
  collectiveId: 654,
  template: 'collective.expense.draft.updated.to.invitee',
  collective: Collective {
    dataValues: {
      id: 654,
      type: 'USER',
      slug: 'user-f24555fc',
      name: 'User Name914ca685',
      legalName: null,
      company: null,
      CreatedByUserId: 445,
      LastEditedByUserId: null,
      ParentCollectiveId: null,
      HostCollectiveId: null,
      hostFeePercent: 10,
      platformFeePercent: null,
      description: 'Description 3665357c',
      longDescription: null,
      expensePolicy: null,
      contributionPolicy: null,
      currency: 'USD',
      image: null,
      backgroundImage: null,
      countryISO: null,
      settings: null,
      data: [Object],
      startsAt: null,
      endsAt: null,
      timezone: null,
      createdAt: ***-11-07T08:43:05.092Z,
      updatedAt: ***-11-07T08:43:05.092Z,
      isActive: false,
      isIncognito: false,
      approvedAt: null,
      twitterHandle: 'twitter53f32fbd',
      repositoryUrl: null,
      website: 'https://example.com/bf7900dc-a575-40fa-8666-42c08735eedb',
      tags: [Array],
      deactivatedAt: null,
      isHostAccount: false,
      plan: null,
      deletedAt: null
    },
    _previousDataValues: {
      id: 654,
      type: 'USER',
      slug: 'user-f24555fc',
      name: 'User Name914ca685',
      legalName: null,
      company: null,
      CreatedByUserId: 445,
      LastEditedByUserId: null,
      ParentCollectiveId: null,
      HostCollectiveId: null,
      hostFeePercent: 10,
      platformFeePercent: null,
      description: 'Description 3665357c',
      longDescription: null,
      expensePolicy: null,
      contributionPolicy: null,
      currency: 'USD',
      image: null,
      backgroundImage: null,
      countryISO: null,
      settings: null,
      data: [Object],
      startsAt: null,
      endsAt: null,
      timezone: null,
      createdAt: ***-11-07T08:43:05.092Z,
      updatedAt: ***-11-07T08:43:05.092Z,
      isActive: false,
      isIncognito: false,
      approvedAt: null,
      twitterHandle: 'twitter53f32fbd',
      repositoryUrl: null,
      website: 'https://example.com/bf7900dc-a575-40fa-8666-42c08735eedb',
      tags: [Array],
      deactivatedAt: null,
      isHostAccount: false,
      plan: null,
      deletedAt: null
    },
    uniqno: 1,
    _changed: Set(0) {},
    _options: {
      isNewRecord: false,
      _schema: null,
      _schemaDelimiter: '',
      raw: true,
      attributes: [Array]
    },
    isNewRecord: false,
    getNextGoal: [AsyncFunction (anonymous)],
    updateSocialLinks: [AsyncFunction (anonymous)],
    getParentCollective: [AsyncFunction (anonymous)],
    getICS: [Function (anonymous)],
    findImage: [Function (anonymous)],
    findImageForUser: [Function (anonymous)],
    getIncognitoMember: [AsyncFunction (anonymous)],
    getIncognitoProfile: [AsyncFunction (anonymous)],
    getOrCreateIncognitoProfile: [AsyncFunction (anonymous)],
    checkAndUpdateImage: [AsyncFunction (anonymous)],
    becomeHost: [AsyncFunction (anonymous)],
    getOrCreateHostPaymentMethod: [AsyncFunction (anonymous)],
    deactivateAsHost: [AsyncFunction (anonymous)],
    enableFeature: [AsyncFunction (anonymous)],
    disableFeature: [AsyncFunction (anonymous)],
    freeze: [AsyncFunction (anonymous)],
    unfreeze: [AsyncFunction (anonymous)],
    isFrozen: [Function (anonymous)],
    hasBudget: [Function (anonymous)],
    hasPublicLocation: [Function (anonymous)],
    activateBudget: [AsyncFunction (anonymous)],
    deactivateBudget: [AsyncFunction (anonymous)],
    canApply: [AsyncFunction (anonymous)],
    canBeUsedAsPayoutProfile: [Function (anonymous)],
    canContact: [Function (anonymous)],
    isApproved: [Function (anonymous)],
    getUrlPath: [AsyncFunction (anonymous)],
    getUser: [AsyncFunction (anonymous)],
    getAdmins: [AsyncFunction (anonymous)],
    getMemberships: [AsyncFunction (anonymous)],
    getAdminUsers: [AsyncFunction (anonymous)],
    getMembersUsers: [AsyncFunction (anonymous)],
    getChildren: [Function (anonymous)],
    getEvents: [Function (anonymous)],
    getProjects: [Function (anonymous)],
    getBackersStats: [Function (anonymous)],
    getNewOrders: [AsyncFunction (anonymous)],
    getCancelledOrders: [AsyncFunction (anonymous)],
    getBackersCount: [Function (anonymous)],
    getIncomingOrders: [Function (anonymous)],
    getOutgoingOrders: [Function (anonymous)],
    getRoleForMemberCollective: [Function (anonymous)],
    getTiersWithUsers: [AsyncFunction (anonymous)],
    getBackerTier: [Function (anonymous)],
    addUserWithRole: [AsyncFunction (anonymous)],
    createMemberCreatedActivity: [AsyncFunction (anonymous)],
    sendNewMemberEmail: [AsyncFunction (anonymous)],
    findOrAddUserWithRole: [Function (anonymous)],
    getHostedCollectives: [AsyncFunction (anonymous)],
    getHostedCollectiveAdmins: [AsyncFunction (anonymous)],
    setLocation: [AsyncFunction (anonymous)],
    updateHostFee: [AsyncFunction (anonymous)],
    updatePlatformFee: [AsyncFunction (anonymous)],
    updateCurrency: [AsyncFunction (anonymous)],
    setCurrency: [AsyncFunction (anonymous)],
    addHost: [AsyncFunction (anonymous)],
    changeHost: [AsyncFunction (anonymous)],
    editMembers: [AsyncFunction (anonymous)],
    editTiers: [Function (anonymous)],
    getExpensesForHost: [Function (anonymous)],
    getExpenses: [Function (anonymous)],
    getUpdates: [Function (anonymous)],
    getPaymentMethod: [AsyncFunction (anonymous)],
    getBalanceWithBlockedFundsAmount: [Function (anonymous)],
    getBalanceWithBlockedFunds: [Function (anonymous)],
    getBalanceAmount: [Function (anonymous)],
    getBalance: [Function (anonymous)],
    getYearlyBudgetAmount: [Function (anonymous)],
    getYearlyBudget: [Function (anonymous)],
    getTotalAmountReceivedAmount: [Function (anonymous)],
    getTotalAmountReceived: [Function (anonymous)],
    getTotalAmountSpentAmount: [Function (anonymous)],
    getTotalAmountSpent: [Function (anonymous)],
    getTotalPaidExpensesAmount: [Function (anonymous)],
    getTotalPaidExpenses: [Function (anonymous)],
    getTotalAmountReceivedTimeSeries: [Function (anonymous)],
    getBalanceTimeSeries: [Function (anonymous)],
    getContributionsAndContributorsCount: [Function (anonymous)],
    getTotalMoneyManaged: [Function (anonymous)],
    getTotalMoneyManagedAmount: [Function (anonymous)],
    getMonthlySpending: [Function (anonymous)],
    transactionsWhereQuery: [Function (anonymous)],
    getTransactions: [Function (anonymous)],
    getTaxType: [Function (anonymous)],
    getTotalTransactions: [AsyncFunction (anonymous)],
    getLatestTransactions: [Function (anonymous)],
    isHost: [Function (anonymous)],
    isHostOf: [Function (anonymous)],
    getHostCollective: [AsyncFunction (anonymous)],
    getHostCollectiveId: [AsyncFunction (anonymous)],
    getCustomerStripeAccount: [Function (anonymous)],
    getHostStripeAccount: [Function (anonymous)],
    getAccountForPaymentProvider: [AsyncFunction (anonymous)],
    getTopBackers: [AsyncFunction (anonymous)],
    getImageUrl: [Function (anonymous)],
    getBackgroundImageUrl: [Function (anonymous)],
    getHostedCollectivesCount: [Function (anonymous)],
    getTotalAddedFunds: [AsyncFunction (anonymous)],
    getTotalTransferwisePayouts: [AsyncFunction (anonymous)],
    getTotalBankTransfers: [AsyncFunction (anonymous)],
    getPlan: [AsyncFunction (anonymous)],
    getHostMetrics: [AsyncFunction (anonymous)],
    setPolicies: [AsyncFunction (anonymous)],
    generateCollectiveCreatedActivity: [AsyncFunction (anonymous)],
    doesUserHaveTotalExpensesOverThreshold: [AsyncFunction (anonymous)]
  },
  skipUnsubscribedCheck: true,
  userId: 445,
  user: User {
    dataValues: {
      id: 445,
      CollectiveId: 654,
      email: 'test-user-p1vtk0vried@emailprovider.com',
      emailWaitingForValidation: null,
      emailConfirmationToken: null,
      createdAt: ***-11-07T08:43:05.091Z,
      updatedAt: ***-11-07T08:43:05.099Z,
      deletedAt: null,
      confirmedAt: ***-11-07T08:43:05.091Z,
      lastLoginAt: null,
      newsletterOptIn: false,
      data: null,
      twoFactorAuthToken: null,
      yubikeyDeviceId: null,
      twoFactorAuthRecoveryCodes: null,
      changelogViewDate: null,
      passwordHash: null,
      passwordUpdatedAt: null
    },
    _previousDataValues: {
      id: 445,
      CollectiveId: 654,
      email: 'test-user-p1vtk0vried@emailprovider.com',
      emailWaitingForValidation: null,
      emailConfirmationToken: null,
      createdAt: ***-11-07T08:43:05.091Z,
      updatedAt: ***-11-07T08:43:05.099Z,
      deletedAt: null,
      confirmedAt: ***-11-07T08:43:05.091Z,
      lastLoginAt: null,
      newsletterOptIn: false,
      data: null,
      twoFactorAuthToken: null,
      yubikeyDeviceId: null,
      twoFactorAuthRecoveryCodes: null,
      changelogViewDate: null,
      passwordHash: null,
      passwordUpdatedAt: null
    },
    uniqno: 1,
    _changed: Set(0) {},
    _options: {
      isNewRecord: false,
      _schema: null,
      _schemaDelimiter: '',
      raw: true,
      attributes: [Array]
    },
    isNewRecord: false,
    _emailChanged: undefined,
    _emailWaitingForValidationChanged: undefined,
    rolesByCollectiveId: undefined,
    jwt: [Function (anonymous)],
    generateSessionToken: [AsyncFunction (anonymous)],
    generateLoginLink: [Function (anonymous)],
    generateResetPasswordLink: [Function (anonymous)],
    setPassword: [AsyncFunction (anonymous)],
    generateConnectedAccountVerifiedToken: [Function (anonymous)],
    getMemberships: [Function (anonymous)],
    getIncognitoProfile: [AsyncFunction (anonymous)],
    populateRoles: [AsyncFunction (anonymous)],
    hasRole: [Function (anonymous)],
    hasRoleInCollectiveOrHost: [Function (anonymous)],
    getAdministratedCollectiveIds: [Function (anonymous)],
    isAdmin: [Function (anonymous)],
    isAdminOfCollective: [Function (anonymous)],
    isAdminOfCollectiveOrHost: [Function (anonymous)],
    isAdminOfPlatform: [Function (anonymous)],
    isAdminOfAnyPlatformAccount: [Function (anonymous)],
    isRoot: [Function (anonymous)],
    isMember: [Function (anonymous)],
    isMemberOfCollective: [Function (anonymous)],
    limitAccount: [AsyncFunction (anonymous)],
    limitFeature: [AsyncFunction (anonymous)],
    unlimitFeature: [AsyncFunction (anonymous)],
    hasDisputedOrders: [AsyncFunction (anonymous)],
    getLastKnownIp: [Function (anonymous)],
    findRelatedUsersByIp: [AsyncFunction (anonymous)],
    findRelatedUsersByConnectedAccounts: [AsyncFunction (anonymous)],
    getCollective: [AsyncFunction (anonymous)],
    collective: Collective {
      dataValues: [Object],
      _previousDataValues: [Object],
      uniqno: 1,
      _changed: Set(0) {},
      _options: [Object],
      isNewRecord: false,
      getNextGoal: [AsyncFunction (anonymous)],
      updateSocialLinks: [AsyncFunction (anonymous)],
      getParentCollective: [AsyncFunction (anonymous)],
      getICS: [Function (anonymous)],
      findImage: [Function (anonymous)],
      findImageForUser: [Function (anonymous)],
      getIncognitoMember: [AsyncFunction (anonymous)],
      getIncognitoProfile: [AsyncFunction (anonymous)],
      getOrCreateIncognitoProfile: [AsyncFunction (anonymous)],
      checkAndUpdateImage: [AsyncFunction (anonymous)],
      becomeHost: [AsyncFunction (anonymous)],
      getOrCreateHostPaymentMethod: [AsyncFunction (anonymous)],
      deactivateAsHost: [AsyncFunction (anonymous)],
      enableFeature: [AsyncFunction (anonymous)],
      disableFeature: [AsyncFunction (anonymous)],
      freeze: [AsyncFunction (anonymous)],
      unfreeze: [AsyncFunction (anonymous)],
      isFrozen: [Function (anonymous)],
      hasBudget: [Function (anonymous)],
      hasPublicLocation: [Function (anonymous)],
      activateBudget: [AsyncFunction (anonymous)],
      deactivateBudget: [AsyncFunction (anonymous)],
      canApply: [AsyncFunction (anonymous)],
      canBeUsedAsPayoutProfile: [Function (anonymous)],
      canContact: [Function (anonymous)],
      isApproved: [Function (anonymous)],
      getUrlPath: [AsyncFunction (anonymous)],
      getUser: [AsyncFunction (anonymous)],
      getAdmins: [AsyncFunction (anonymous)],
      getMemberships: [AsyncFunction (anonymous)],
      getAdminUsers: [AsyncFunction (anonymous)],
      getMembersUsers: [AsyncFunction (anonymous)],
      getChildren: [Function (anonymous)],
      getEvents: [Function (anonymous)],
      getProjects: [Function (anonymous)],
      getBackersStats: [Function (anonymous)],
      getNewOrders: [AsyncFunction (anonymous)],
      getCancelledOrders: [AsyncFunction (anonymous)],
      getBackersCount: [Function (anonymous)],
      getIncomingOrders: [Function (anonymous)],
      getOutgoingOrders: [Function (anonymous)],
      getRoleForMemberCollective: [Function (anonymous)],
      getTiersWithUsers: [AsyncFunction (anonymous)],
      getBackerTier: [Function (anonymous)],
      addUserWithRole: [AsyncFunction (anonymous)],
      createMemberCreatedActivity: [AsyncFunction (anonymous)],
      sendNewMemberEmail: [AsyncFunction (anonymous)],
      findOrAddUserWithRole: [Function (anonymous)],
      getHostedCollectives: [AsyncFunction (anonymous)],
      getHostedCollectiveAdmins: [AsyncFunction (anonymous)],
      setLocation: [AsyncFunction (anonymous)],
      updateHostFee: [AsyncFunction (anonymous)],
      updatePlatformFee: [AsyncFunction (anonymous)],
      updateCurrency: [AsyncFunction (anonymous)],
      setCurrency: [AsyncFunction (anonymous)],
      addHost: [AsyncFunction (anonymous)],
      changeHost: [AsyncFunction (anonymous)],
      editMembers: [AsyncFunction (anonymous)],
      editTiers: [Function (anonymous)],
      getExpensesForHost: [Function (anonymous)],
      getExpenses: [Function (anonymous)],
      getUpdates: [Function (anonymous)],
      getPaymentMethod: [AsyncFunction (anonymous)],
      getBalanceWithBlockedFundsAmount: [Function (anonymous)],
      getBalanceWithBlockedFunds: [Function (anonymous)],
      getBalanceAmount: [Function (anonymous)],
      getBalance: [Function (anonymous)],
      getYearlyBudgetAmount: [Function (anonymous)],
      getYearlyBudget: [Function (anonymous)],
      getTotalAmountReceivedAmount: [Function (anonymous)],
      getTotalAmountReceived: [Function (anonymous)],
      getTotalAmountSpentAmount: [Function (anonymous)],
      getTotalAmountSpent: [Function (anonymous)],
      getTotalPaidExpensesAmount: [Function (anonymous)],
      getTotalPaidExpenses: [Function (anonymous)],
      getTotalAmountReceivedTimeSeries: [Function (anonymous)],
      getBalanceTimeSeries: [Function (anonymous)],
      getContributionsAndContributorsCount: [Function (anonymous)],
      getTotalMoneyManaged: [Function (anonymous)],
      getTotalMoneyManagedAmount: [Function (anonymous)],
      getMonthlySpending: [Function (anonymous)],
      transactionsWhereQuery: [Function (anonymous)],
      getTransactions: [Function (anonymous)],
      getTaxType: [Function (anonymous)],
      getTotalTransactions: [AsyncFunction (anonymous)],
      getLatestTransactions: [Function (anonymous)],
      isHost: [Function (anonymous)],
      isHostOf: [Function (anonymous)],
      getHostCollective: [AsyncFunction (anonymous)],
      getHostCollectiveId: [AsyncFunction (anonymous)],
      getCustomerStripeAccount: [Function (anonymous)],
      getHostStripeAccount: [Function (anonymous)],
      getAccountForPaymentProvider: [AsyncFunction (anonymous)],
      getTopBackers: [AsyncFunction (anonymous)],
      getImageUrl: [Function (anonymous)],
      getBackgroundImageUrl: [Function (anonymous)],
      getHostedCollectivesCount: [Function (anonymous)],
      getTotalAddedFunds: [AsyncFunction (anonymous)],
      getTotalTransferwisePayouts: [AsyncFunction (anonymous)],
      getTotalBankTransfers: [AsyncFunction (anonymous)],
      getPlan: [AsyncFunction (anonymous)],
      getHostMetrics: [AsyncFunction (anonymous)],
      setPolicies: [AsyncFunction (anonymous)],
      generateCollectiveCreatedActivity: [AsyncFunction (anonymous)],
      doesUserHaveTotalExpensesOverThreshold: [AsyncFunction (anonymous)]
    }
  },
  isTransactional: false,
  listId: 'user-f24555fc::collective.expense.draft.updated.to.invitee',
  accountSlug: 'user-f24555fc',
  text: 'AN EXPENSE FOR TEST COLLECTIVE 22AE07CF HAS BEEN UPDATED.\n' +
    '\n' +
    '\n' +
    'THIS IS A TEST. [http://localhost:3000/collective-0d7af46f/expenses/51]\n' +
    '\n' +
    'Payee: User Name08bcdba3 [http://localhost:3000/user-0587f2b8]\n' +
    '\n' +
    '\n' +
    '\n' +
    'View Expense\n' +
    '[http://localhost:3000/collective-0d7af46f/expenses/51]\n' +
    '\n' +
    '\n' +
    '\n' +
    '[http://localhost:3000/static/images/email/logo-email-footer@2x.png]\n' +
    'http://localhost:3000\n' +
    '\n' +
    'We can do great things together\n' +
    '\n' +
    'You can also follow us on Twitter [https://twitter.com/OpenCollect] or come chat\n' +
    'with us on our public Discord [https://discord.opencollective.com/].\n' +
    '\n' +
    'Made with ❤️ from all over the world\n' +
    '[https://docs.opencollective.com/help/about/team]',
  tag: 'collective.expense.draft.updated.to.invitee',
  unsubscribeUrl: undefined,
  bcc: undefined
}
      at Context.<anonymous> (test/server/graphql/v2/mutation/ExpenseMutations.test.js:1986:37)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
