### ISSUE TITLE
Failure when running db:setup for test environment

### ISSUE THREAD

**Issue by aguywithcode** [opencollective/opencollective#6912]
**Describe the bug**
The db:setup script fails in local test environment.

**To Reproduce**
1. Set NODE_ENV=test in environment
2. Execute 'npm run db:setup'
3. See error

```
{
  "date": "Sun Jul 30 2023 21:43:57 GMT-0700 (Pacific Daylight Time)",
  "error": {
    "name": "SequelizeDatabaseError",
    "original": {
      "code": "42846",
      "file": "parse_expr.c",
      "length": 167,
      "line": "2822",
      "name": "error",
      "position": "605",
      "routine": "transformTypeCast",
      "severity": "ERROR",
      "sql": "ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP NOT NULL;ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP DEFAULT;DO 'BEGIN CREATE TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\" AS ENUM(''email'', ''incognito'', ''account'', ''expenses'', ''orders'', ''transactions'', ''virtualCards'', ''updates'', ''conversations'', ''webhooks'', ''host'', ''applications'', ''connectedAccounts'', ''root''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\"[] USING (\"scope\"::\"public\".\"enum_OAuthAuthorizationCodes_scope\");"
    },
    "parameters": {},
    "parent": {
      "code": "42846",
      "file": "parse_expr.c",
      "length": 167,
      "line": "2822",
      "name": "error",
      "position": "605",
      "routine": "transformTypeCast",
      "severity": "ERROR",
      "sql": "ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP NOT NULL;ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP DEFAULT;DO 'BEGIN CREATE TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\" AS ENUM(''email'', ''incognito'', ''account'', ''expenses'', ''orders'', ''transactions'', ''virtualCards'', ''updates'', ''conversations'', ''webhooks'', ''host'', ''applications'', ''connectedAccounts'',''root''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\"[] USING (\"scope\"::\"public\".\"enum_OAuthAuthorizationCodes_scope\");"
    },
    "sql": "ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP NOT NULL;ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" DROP DEFAULT;DO 'BEGIN CREATE TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\" AS ENUM(''email'', ''incognito'', ''account'', ''expenses'', ''orders'', ''transactions'', ''virtualCards'', ''updates'', ''conversations'', ''webhooks'', ''host'', ''applications'', ''connectedAccounts'', ''root''); EXCEPTION WHEN duplicate_object THEN null; END';ALTER TABLE \"OAuthAuthorizationCodes\" ALTER COLUMN \"scope\" TYPE \"public\".\"enum_OAuthAuthorizationCodes_scope\"[] USING (\"scope\"::\"public\".\"enum_OAuthAuthorizationCodes_scope\");"
  },
  "exception": true,
  "os": {
    "loadavg": [
      4.91162109375,
      4.69140625,
      4.6845703125
    ],
    "uptime": 381982
  },
  "process": {
    "argv": [
      "node",
      "/Users/michael/projects/opencollective/api/scripts/db_setup.js"
    ],
    "cwd": "/Users/michael/projects/opencollective/api",
    "execPath": "/Users/michael/.nvm/versions/node/v18.16.1/bin/node",
    "gid": 20,
    "memoryUsage": {
      "arrayBuffers": 1022258,
      "external": 2521699,
      "heapTotal": 503709696,
      "heapUsed": 325691776,
      "rss": 609124352
    },
    "pid": 94268,
    "uid": 501,
    "version": "v18.16.1"
  },
  "stack": "Error: \n    at Query.run (/Users/michael/projects/opencollective/api/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at /Users/michael/projects/opencollective/api/node_modules/sequelize/src/sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Function.sync (/Users/michael/projects/opencollective/api/node_modules/sequelize/src/model.js:1408:11)\n    at Sequelize._syncModelsWithCyclicReferences (/Users/michael/projects/opencollective/api/node_modules/sequelize/src/sequelize.js:861:7)",
  "trace": [
    {
      "column": 25,
      "file": "/Users/michael/projects/opencollective/api/node_modules/sequelize/src/dialects/postgres/query.js",
      "function": "Query.run",
      "line": 76,
      "method": "run",
      "native": false
    },
    {
      "column": 28,
      "file": "/Users/michael/projects/opencollective/api/node_modules/sequelize/src/sequelize.js",
      "function": null,
      "line": 650,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "node:internal/process/task_queues",
      "function": "processTicksAndRejections",
      "line": 95,
      "method": null,
      "native": false
    },
    {
      "column": 11,
      "file": "/Users/michael/projects/opencollective/api/node_modules/sequelize/src/model.js",
      "function": "Function.sync",
      "line": 1408,
      "method": "sync",
      "native": false
    },
    {
      "column": 7,
      "file": "/Users/michael/projects/opencollective/api/node_modules/sequelize/src/sequelize.js",
      "function": "Sequelize._syncModelsWithCyclicReferences",
      "line": 861,
      "method": "_syncModelsWithCyclicReferences",
      "native": false
    }
  ]
}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node 18.16.1

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@aguywithcode what's your Postgres server version?

**Comment by aguywithcode** [comment]
13.7

**Comment by aguywithcode** [comment]
> @aguywithcode what's your Postgres server version?

13.7 running in Docker if that makes a difference.

**Comment by Betree** [comment]
> 13.7 running in Docker if that makes a difference.

It shouldn't, that's what I'm using too. I wasn't able to reproduce, but let's keep this issue open in case anyone else faces it.
