### ISSUE TITLE
Authenticated SSR: hydration errors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7525]
This issue aims to track the hydration errors related to https://github.com/opencollective/opencollective/issues/7476.

**Comment by Betree** [comment]
URL: http://localhost:3000/dashboard
Location: Hos Dashboard > Account Switcher
Description: It's likely that the cookie that informs the account switcher of the "latest picked account" is not considered by the API.

```
Warning: Prop `type` did not match. Server: "USER" Client: "ORGANIZATION"
    at div
    at P (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19658)
    at Avatar (webpack-internal:///./components/Avatar.tsx:76:11)
    at div
    at P (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19658)
    at Option (webpack-internal:///./components/dashboard/AccountSwitcher.tsx:150:11)
    at button
    at P (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19658)
    at div
    at P (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19658)
    at div
    at eval (webpack-internal:///./components/StyledDropdown.js:41:11)
    at P (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19658)
    at AccountSwitcher (webpack-internal:///./components/dashboard/AccountSwitcher.tsx:358:11)
    at div
    at div
    at div
    at AdminPanelSideBar (webpack-internal:///./components/dashboard/SideBar.tsx:28:11)
    at div
    at main
    at Body (webpack-internal:///./components/Body.js:14:1)
    at div
    at Page (webpack-internal:///./components/Page.tsx:19:11)
    at WithUser
    at div
    at DashboardPage (webpack-internal:///./pages/dashboard.tsx:191:70)
    at NewsAndUpdatesProvider (webpack-internal:///./components/NewsAndUpdatesProvider.js:20:11)
    at ModalProvider (webpack-internal:///./components/ModalContext.tsx:114:11)
    at UserProvider (webpack-internal:///./components/UserProvider.js:82:9)
    at injectIntl(UserProvider)
    at WithRouterWrapper (webpack-internal:///./node_modules/next/dist/client/with-router.js:18:43)
    at W
    at withLoggedInUser (webpack-internal:///./lib/hooks/withLoggedInUser.js:64:13)
    at ApolloConsumer
    at WithApollo (webpack-internal:///./node_modules/@apollo/client/react/hoc/withApollo.js:29:32)
    at injectIntl(withApollo(withLoggedInUser(undefined)))
    at Provider (webpack-internal:///./node_modules/@radix-ui/react-context/dist/index.mjs:48:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (webpack-internal:///./node_modules/@radix-ui/react-tooltip/dist/index.mjs:73:29)
    at IntlProvider (webpack-internal:///./components/intl/IntlProvider.tsx:26:11)
    at Elements (webpack-internal:///./node_modules/@stripe/react-stripe-js/dist/react-stripe.umd.js:471:30)
    at StripeProvider (webpack-internal:///./components/StripeProvider.js:53:9)
    at Le (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:17336)
    at ApolloProvider (webpack-internal:///./node_modules/@apollo/client/react/context/ApolloProvider.js:14:21)
    at OpenCollectiveFrontendApp (webpack-internal:///./pages/_app.js:307:9)
    at TwoFactorAuthProvider (webpack-internal:///./lib/two-factor-authentication/TwoFactorAuthenticationContext.js:153:11)
    at W
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:81:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/client/components/react-dev-overlay/pages/ErrorBoundary.js:41:9)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/client/components/react-dev-overlay/pages/ReactDevOverlay.js:33:11)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:81:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:189:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:413:11) 
```

**Comment by Betree** [comment]
URL: http://localhost:3000/apex/expenses/new

![image](https://github.com/user-attachments/assets/f894ac77-9c70-423a-8121-6ef736b2fe24)

**Comment by Betree** [comment]
URL: http://localhost:3000/dashboard/my-collective/updates/new

![image](https://github.com/user-attachments/assets/d34edf5a-10e7-4d0b-8a36-a8c40005f46d)
