### ISSUE TITLE
Website crashing

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#83]
This is what caused the crash on Saturday morning. Papertrail of `website`:

```
May 14 01:18:43 opencollective-prod-website heroku/router:  at=info method=GET path="/react-static-boilerplate/backer/2/website" host=website.opencollective.com request_id=b58b83c8-0058-481d-87c7-f95850fceb65 fwd="68.180.229.231,104.236.172.72" dyno=web.1 connect=1ms service=38ms status=302 bytes=329 
May 14 01:18:43 opencollective-prod-website app/web.1:  GET /react-static-boilerplate/backer/2/website 302 33.089 ms - 73 
May 14 01:18:46 opencollective-prod-website app/web.1:  /app/server/controllers/banner.js:98 
May 14 01:18:46 opencollective-prod-website app/web.1:          var contentType = r.headers['content-type']; 
May 14 01:18:46 opencollective-prod-website app/web.1:                             ^ 
May 14 01:18:46 opencollective-prod-website app/web.1:  TypeError: Cannot read property 'headers' of undefined 
May 14 01:18:46 opencollective-prod-website app/web.1:      at Request._callback (banner.js:77:29) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at self.callback (/app/node_modules/request/request.js:200:22) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at emitOne (events.js:90:13) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at Request.emit (events.js:182:7) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at Request.onRequestError (/app/node_modules/request/request.js:831:8) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at emitOne (events.js:90:13) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at ClientRequest.emit (events.js:182:7) 
May 14 01:18:46 opencollective-prod-website app/web.1:      at TLSSocket.socketErrorListener (_http_client.js:306:9) 
May 14 01:18:46 opencollective-prod-website heroku/router:  at=error code=H13 desc="Connection closed without response" method=GET path="/mochajs/sponsor/0/avatar" host=website.opencollective.com request_id=3aea9045-3c44-4b54-8322-1759691840fb fwd="54.146.12.55,104.236.172.72" dyno=web.1 connect=2ms service=9952ms status=503 bytes=0 
May 14 01:18:46 opencollective-prod-website app/web.1:      at TLSSocket.emit (events.js:182:7) 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! Linux 3.13.0-79-generic 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start" 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! node v5.11.0 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! npm  v3.8.6 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! code ELIFECYCLE 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! opencollective-website@0.1.96 start: `NODE_CONFIG_DIR=./server/config node server` 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! Exit status 1 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR!  
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! Failed at the opencollective-website@0.1.96 start script 'NODE_CONFIG_DIR=./server/config node server'. 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! Make sure you have the latest version of node.js and npm installed. 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! If you do, this is most likely a problem with the opencollective-website package, 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! not with npm itself. 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! Tell the author that this fails on your system: 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR!     NODE_CONFIG_DIR=./server/config node server 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR! You can get information on how to open an issue for this project with: 
May 14 01:18:46 opencollective-prod-website app/web.1:  npm ERR!     npm bugs opencollective-website 
May 14 01:18:47 opencollective-prod-website app/web.1:  npm ERR! Or if that isn't available, you can get their info via: 
May 14 01:18:47 opencollective-prod-website app/web.1:  npm ERR!     npm owner ls opencollective-website 
May 14 01:18:47 opencollective-prod-website app/web.1:  npm ERR! There is likely additional logging output above. 
May 14 01:18:47 opencollective-prod-website app/web.1:  npm ERR! Please include the following file with any support request: 
May 14 01:18:47 opencollective-prod-website app/web.1:  npm ERR!     /app/npm-debug.log 
May 14 01:18:48 opencollective-prod-website heroku/web.1:  Process exited with status 1 
May 14 01:18:48 opencollective-prod-website heroku/web.1:  State changed from up to crashed 
```

Papertrail of api:

```
May 14 01:18:43 opencollective-prod-api heroku/router:  at=info method=GET path="/groups/react-static-boilerplate/users?api_key=30DV4OgF6jXO8WeaWy503AZnO1GF3gHv" host=opencollective-prod-api.herokuapp.com request_id=a311cd03-cfe6-4541-8be2-d1273ae6cf7d fwd="54.227.8.208" dyno=web.1 connect=1ms service=14ms status=200 bytes=1160 
May 14 01:18:43 opencollective-prod-api app/web.1:  Executing (default): SELECT "id", "name", "mission", "description", "longDescription", "budget", "burnrate", "currency", "logo", "video", "image", "backgroundImage", "expensePolicy", "tiers", "hostFeePercent", "createdAt", "updatedAt", "isPublic", "slug", "twitterHandle", "website", "deletedAt" FROM "Groups" AS "Group" WHERE ("Group"."deletedAt" IS NULL AND "Group"."slug" = 'react-static-boilerplate') LIMIT 1; 
May 14 01:18:43 opencollective-prod-api app/web.1:  Executing (default): WITH total_donations AS ( 
May 14 01:18:43 opencollective-prod-api app/web.1:          SELECT 
May 14 01:18:43 opencollective-prod-api app/web.1:            max("UserId") as "UserId", 
May 14 01:18:43 opencollective-prod-api app/web.1:            SUM(amount/100) as amount 
May 14 01:18:43 opencollective-prod-api app/web.1:          FROM "Donations" d 
May 14 01:18:43 opencollective-prod-api app/web.1:          WHERE d."GroupId" = 63 AND d.amount >= 0 
May 14 01:18:43 opencollective-prod-api app/web.1:          GROUP BY "UserId" 
May 14 01:18:43 opencollective-prod-api app/web.1:        ) 
May 14 01:18:43 opencollective-prod-api app/web.1:        SELECT 
May 14 01:18:43 opencollective-prod-api app/web.1:          ug."UserId" as id, 
May 14 01:18:43 opencollective-prod-api app/web.1:          ug."createdAt" as "createdAt", 
May 14 01:18:43 opencollective-prod-api app/web.1:          u.name as name, 
May 14 01:18:43 opencollective-prod-api app/web.1:          ug.role as role, 
May 14 01:18:43 opencollective-prod-api app/web.1:          u.avatar as avatar, 
May 14 01:18:43 opencollective-prod-api app/web.1:          u.website as website, 
May 14 01:18:43 opencollective-prod-api app/web.1:          u."twitterHandle" as "twitterHandle", 
May 14 01:18:43 opencollective-prod-api app/web.1:          td.amount as "totalDonations" 
May 14 01:18:43 opencollective-prod-api app/web.1:        FROM "UserGroups" ug 
May 14 01:18:43 opencollective-prod-api app/web.1:        LEFT JOIN "Users" u ON u.id = ug."UserId" 
May 14 01:18:43 opencollective-prod-api app/web.1:        LEFT JOIN total_donations td ON td."UserId" = ug."UserId" 
May 14 01:18:43 opencollective-prod-api app/web.1:        WHERE ug."GroupId" = 63 
May 14 01:18:43 opencollective-prod-api app/web.1:        ORDER BY "totalDonations" DESC, ug."createdAt" ASC 
May 14 01:18:43 opencollective-prod-api app/web.1:  GET /groups/react-static-boilerplate/users?api_key=30DV4OgF6jXO8WeaWy503AZnO1GF3gHv 200 11.685 ms - 889
```

@xdamman I'm not that familiar with the banner code. See anything off?

**Comment by asood123** [comment]
Related to https://github.com/OpenCollective/OpenCollective/issues/82

**Comment by carlosascari** [comment]
I couldn't find the line `var contentType = r.headers['content-type'];` in any recent commit
https://github.com/OpenCollective/opencollective-website/commits/master/server/controllers/banner.js

**Comment by asood123** [comment]
It's this line:
https://github.com/OpenCollective/opencollective-website/blob/master/server/controllers/banner.js#L77.
I think it might be related to issue:82, where API is overwhelmed and
doesn't return anything?

**Comment by carlosascari** [comment]
I don't see how the api server was overwhelmed, theres not enough evidence that points to that IMHO
```
76      request({url: imageUrl, encoding: null}, (e, r, data) => {
77        const contentType = r.headers['content-type'];
 ```

Right now we can add a error check line before line 77 
```
if (e) {
    console.error(e)
    res.status(500).end() // OR send a placeholder svg image
    return
}
````

As a fallback and so we get the error stack, what do you think @asood123 ?

**Comment by asood123** [comment]
makes sense. let's do it.

**Comment by piamancini** [comment]
@asood123 @carlosascari this had now activity in 25 days, should be close it?
