### ISSUE TITLE
user trying to make a subscription get an unexpected system error

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#887]
https://opencollective.com/chsf/order/709
hits submit and fails
![fullscreen-3](https://user-images.githubusercontent.com/3671070/35934927-e6ba6182-0c0c-11e8-92d2-0ae0c3489ab9.jpg)

Also note tier name is failing

**Comment by asood123** [comment]
His user account was created without a `CollectiveId` listed (so no collective created). That's causing all the issues. Here is the error from logs:

```
Feb 06 09:02:39 opencollective-prod-api app/web.1: >>> createOrder mutation error:  { SequelizeDatabaseError: value too long for type character varying(255) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:356:16) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at tryCatcher (/app/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Promise._settlePromiseFromHandler (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Promise._settlePromise (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Promise._settlePromise0 (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Promise._settlePromises (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:689:18) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Async._drainQueue (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Async._drainQueues (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Immediate.Async.drainQueues (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at Immediate.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:22) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at runCallback (timers.js:781:20) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at tryOnImmediate (timers.js:743:5) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:     at processImmediate [as _immediateCallback] (timers.js:714:5) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:   name: 'SequelizeDatabaseError', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:   parent:  
Feb 06 09:02:39 opencollective-prod-api app/web.1:    { error: value too long for type character varying(255) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at emitOne (events.js:115:13) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.emit (events.js:210:7) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at addChunk (_stream_readable.js:266:12) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at readableAddChunk (_stream_readable.js:253:11) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.Readable.push (_stream_readable.js:211:10) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSWrap.onread (net.js:585:20) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      name: 'error', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      length: 99, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      severity: 'ERROR', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      code: '22001', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      detail: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      hint: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      position: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      internalPosition: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      internalQuery: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      where: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      schema: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      table: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      column: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      dataType: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      constraint: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      file: 'varchar.c', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      line: '624', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      routine: 'varchar', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      sql: 'INSERT INTO "Collectives" ("id","type","slug","name","CreatedByUserId","hostFeePercent","description","currency","data","createdAt","updatedAt","isActive","twitterHandle","website","isSupercollective") VALUES (DEFAULT,\'USER\',\'paradiseinc\',\'Jay Chodagam\',10926,5,\'Jay Chodagam is a meditation teacher, TEDx speaker and producer of Peace in the Park festival and SPIRIT Summit. While getting his master’s degree in Engineering at the University of Texas at Austin, Jay came to the realization that a life of fulfillment trumps a life of achievement. Since then, he has been a proponent of meditation training and “being” before “doing” at workplaces, schools, prisons and hospitals.  As a student and teacher with the Raja Yoga meditation for over 16 years, Jay regularly leads retreats and workshops around the world.\',\'USD\',\'{"UserId":10926}\',\'2018-02-06 17:02:39.049 +00:00\',\'2018-02-06 17:02:39.049 +00:00\',true,\'paradiseinc\',\'www.bksanfrancisco.org\',false) RETURNING *;' }, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:   original:  
Feb 06 09:02:39 opencollective-prod-api app/web.1:    { error: value too long for type character varying(255) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at emitOne (events.js:115:13) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.emit (events.js:210:7) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at addChunk (_stream_readable.js:266:12) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at readableAddChunk (_stream_readable.js:253:11) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSSocket.Readable.push (_stream_readable.js:211:10) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:        at TLSWrap.onread (net.js:585:20) 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      name: 'error', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      length: 99, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      severity: 'ERROR', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      code: '22001', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      detail: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      hint: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      position: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      internalPosition: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      internalQuery: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      where: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      schema: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      table: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      column: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      dataType: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      constraint: undefined, 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      file: 'varchar.c', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      line: '624', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      routine: 'varchar', 
Feb 06 09:02:39 opencollective-prod-api app/web.1:      sql: 'INSERT INTO "Collectives" ("id","type","slug","name","CreatedByUserId","hostFeePercent","description","currency","data","createdAt","updatedAt","isActive","twitterHandle","website","isSupercollective") VALUES (DEFAULT,\'USER\',\'paradiseinc\',\'Jay Chodagam\',10926,5,\'Jay Chodagam is a meditation teacher, TEDx speaker and producer of Peace in the Park festival and SPIRIT Summit. While getting his master’s degree in Engineering at the University of Texas at Austin, Jay came to the realization that a life of fulfillment trumps a life of achievement. Since then, he has been a proponent of meditation training and “being” before “doing” at workplaces, schools, prisons and hospitals.  As a student and teacher with the Raja Yoga meditation for over 16 years, Jay regularly leads retreats and workshops around the world.\',\'USD\',\'{"UserId":10926}\',\'2018-02-06 17:02:39.049 +00:00\',\'2018-02-06 17:02:39.049 +00:00\',true,\'paradiseinc\',\'www.bksanfrancisco.org\',false) RETURNING *;' }, ****

**Comment by piamancini** [comment]
removing the high priority on this since user is now unblocked to make a contribution

**Comment by piamancini** [comment]
this was also referenced https://github.com/opencollective/opencollective/issues/654 and https://github.com/opencollective/opencollective/issues/651
